version: '3.9'
services:
    angular:
        build:
            context: .
            dockerfile: Dockerfile-dev
        container_name: angular-dev-mireceta
        ports:
          - "4200:4200"
          - "49153:49153"
        volumes:
          - "/usr/src/app/node_modules"
          - ".:/usr/src/app"